# Generated by Django 3.0.8 on 2020-07-12 14:26

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200712_1327'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tutorial',
            managers=[
                ('tutorials', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 14, 26, 31, 302906), verbose_name='Date Published'),
        ),
    ]
