# Generated by Django 3.0.8 on 2020-07-12 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200712_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 14, 29, 32, 568380), verbose_name='Date Published'),
        ),
    ]
